package com.xuhailiang5794.ik.support.tp.mapper;

import com.xuhailiang5794.ik.support.tp.entity.Partner;

public interface PartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tp_partner
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tp_partner
     *
     * @mbg.generated
     */
    int insert(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tp_partner
     *
     * @mbg.generated
     */
    int insertSelective(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tp_partner
     *
     * @mbg.generated
     */
    Partner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tp_partner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tp_partner
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Partner record);
}