# mybatis generator代码生成数据库配置
generatorDriverClass: com.mysql.jdbc.Driver
generatorConnectionURL: jdbc:mysql://127.0.0.1:3306/ik
generatorUserId: ik
generatorPassword: 123456

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ik?useUnicode=true&characterEncoding=utf-8
    username: ik
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          default-requeue-rejected: true
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
maximumPoolSize: 15