package com.xuhailiang5794.ik.business.indicator.mapper;

import com.xuhailiang5794.ik.business.indicator.entity.Expression;
import java.util.List;
import java.util.Map;

public interface ExpressionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_expression
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_expression
     *
     * @mbg.generated
     */
    int insert(Expression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_expression
     *
     * @mbg.generated
     */
    int insertSelective(Expression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_expression
     *
     * @mbg.generated
     */
    Expression selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_expression
     *
     * @mbg.generated
     */
    List<Expression> selectByCondition(Map<String, Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_expression
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Expression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_expression
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Expression record);
}