package com.xuhailiang5794.ik.business.indicator.mapper;

import com.xuhailiang5794.ik.business.indicator.entity.IndicatorLibrary;
import java.util.List;
import java.util.Map;

public interface IndicatorLibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_library
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_library
     *
     * @mbg.generated
     */
    int insert(IndicatorLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_library
     *
     * @mbg.generated
     */
    int insertSelective(IndicatorLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_library
     *
     * @mbg.generated
     */
    IndicatorLibrary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_library
     *
     * @mbg.generated
     */
    List<IndicatorLibrary> selectByCondition(Map<String, Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_library
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IndicatorLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_library
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndicatorLibrary record);
}