package com.xuhailiang5794.ik.business.indicator.mapper;

import com.xuhailiang5794.ik.business.indicator.entity.IndicatorWhere;

public interface IndicatorWhereMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_where
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_where
     *
     * @mbg.generated
     */
    int insert(IndicatorWhere record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_where
     *
     * @mbg.generated
     */
    int insertSelective(IndicatorWhere record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_where
     *
     * @mbg.generated
     */
    IndicatorWhere selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_where
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IndicatorWhere record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_where
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndicatorWhere record);
}