package com.xuhailiang5794.ik.business.indicator.mapper;

import com.xuhailiang5794.ik.business.indicator.entity.IndicatorWhereCode;
import java.util.List;
import java.util.Map;

public interface IndicatorWhereCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_where_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_where_code
     *
     * @mbg.generated
     */
    int insert(IndicatorWhereCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_where_code
     *
     * @mbg.generated
     */
    int insertSelective(IndicatorWhereCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_where_code
     *
     * @mbg.generated
     */
    IndicatorWhereCode selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_where_code
     *
     * @mbg.generated
     */
    List<IndicatorWhereCode> selectByCondition(Map<String, Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_where_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IndicatorWhereCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_where_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndicatorWhereCode record);
}