package com.xuhailiang5794.ik.business.enterprise.mapper;

import com.xuhailiang5794.ik.business.enterprise.entity.EnterpriseList;
import java.util.List;
import java.util.Map;

public interface EnterpriseListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_list
     *
     * @mbg.generated
     */
    int insert(EnterpriseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_list
     *
     * @mbg.generated
     */
    int insertSelective(EnterpriseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_list
     *
     * @mbg.generated
     */
    EnterpriseList selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_list
     *
     * @mbg.generated
     */
    List<EnterpriseList> selectByCondition(Map<String, Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EnterpriseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EnterpriseList record);
}