package com.xuhailiang5794.ik.model;

public class UserKey {
    private String dbcode;

    private String id;

    public String getDbcode() {
        return dbcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_national_tree.dbcode
     *
     * @param dbcode the value for data_national_tree.dbcode
     *
     * @mbggenerated
     */
    public void setDbcode(String dbcode) {
        this.dbcode = dbcode == null ? null : dbcode.trim();
    }

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_national_tree.id
     *
     * @param id the value for data_national_tree.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}