package com.xuhailiang5794.ik.mapper;

import com.xuhailiang5794.ik.model.User;
import com.xuhailiang5794.ik.model.UserKey;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_national_tree
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_national_tree
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_national_tree
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_national_tree
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_national_tree
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_national_tree
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
}